# R7.1: the control library. Fixed catalogue of control types the system
# maintains -- a Control instance's control_type must be one of these,
# same relationship as RiskFactor.category is to RISK_CATEGORIES.
CONTROL_LIBRARY = [
    "KYC_CUSTOMER_DUE_DILIGENCE",
    "ENHANCED_DUE_DILIGENCE",
    "BENEFICIAL_OWNERSHIP_VERIFICATION",
    "SANCTIONS_SCREENING",
    "TRANSACTION_MONITORING",
    "FRAUD_MONITORING",
    "TRANSACTION_LIMITS",
    "GEOGRAPHIC_RESTRICTIONS",
    "CUSTOMER_RISK_MONITORING",
    "VENDOR_DUE_DILIGENCE",
    "INVESTIGATION_PROCESSES",
    "REGULATORY_REPORTING",
]

# Suggested control types per risk category (RISK_CATEGORIES in
# app/schemas/risk_factor.py) -- a starting point offered when mapping
# controls to a newly identified risk, not an enforced restriction (any
# control in CONTROL_LIBRARY may be mapped to any risk).
SUGGESTED_CONTROLS_BY_CATEGORY: dict[str, list[str]] = {
    "PRODUCT_SERVICE_RISK": ["KYC_CUSTOMER_DUE_DILIGENCE", "TRANSACTION_MONITORING"],
    "CUSTOMER_SEGMENT_RISK": [
        "KYC_CUSTOMER_DUE_DILIGENCE",
        "ENHANCED_DUE_DILIGENCE",
        "CUSTOMER_RISK_MONITORING",
    ],
    "GEOGRAPHIC_RISK": [
        "SANCTIONS_SCREENING",
        "GEOGRAPHIC_RESTRICTIONS",
        "ENHANCED_DUE_DILIGENCE",
    ],
    "DELIVERY_CHANNEL_RISK": ["KYC_CUSTOMER_DUE_DILIGENCE", "FRAUD_MONITORING"],
    "TRANSACTION_ACTIVITY_RISK": ["TRANSACTION_MONITORING", "TRANSACTION_LIMITS"],
    "TECHNOLOGY_DEVELOPMENT_RISK": ["FRAUD_MONITORING", "INVESTIGATION_PROCESSES"],
    "THIRD_PARTY_VENDOR_RISK": ["VENDOR_DUE_DILIGENCE"],
    "OWNERSHIP_ENTITY_COMPLEXITY_RISK": ["BENEFICIAL_OWNERSHIP_VERIFICATION"],
    "FINANCIAL_CRIME_TYPOLOGY_RISK": [
        "SANCTIONS_SCREENING",
        "TRANSACTION_MONITORING",
        "INVESTIGATION_PROCESSES",
    ],
    "CONTROL_ENVIRONMENT_RISK": ["REGULATORY_REPORTING", "INVESTIGATION_PROCESSES"],
}
